### PR TITLE
Fix taxsim_cols() function

### PR DESCRIPTION
**Pull request by thomascwells**
Adds a couple missing columns from the checker function as mentioned in #6. I think all cols are now included, but it could be worth checking to be sure. I'm not sure where to find the "complete" list of allowable input columns in v35 of TAXSIM.

### CODE REVIEW

**Comment by shanejorr** [comment]
Thank you for this and it does look like all column are included now. Not sure what happended before.

I have been taking the spelling of the columns from bolded items on https://users.nber.org/~taxsim/taxsim35/. in looking at the column names you identified by clicking 'calculate this single taxpayer', I've noticed differences in spelling for at least two columns: taxsimid / taxsim and ui / sui.

I sent a message to the TAXSIM person at the NBER on this issue. I will bring in the request once I hear back.

**Comment by thomascwells** [comment]
I also noticed the spelling differences while digging in. I don't quite know how to sort it out. I think the proposed function works, but I also haven't tested all of the input columns. Hopefully Daniel can shed some light. 

An idea for future work: automated tests for all possible columns. 

It would be ideal if he could open source the underlying code. That would make it much easier to detect version updates and subsequent changes to the "API."

**Comment by shanejorr** [comment]
I merged the request. Thanks!

I received a reply from Daniel. The column names that show up after clicking 'calculate using this file's data' are the correct names. He thanks you for noting the discrepency. He has already updated the column names in bold on https://users.nber.org/~taxsim/taxsim35/.

I agree that a test of column names would be useful and I will do this soon. My thinking is to use a Selenium WebDriver with RSelenium to click on the 'calculate using this file's data' button and then scrape the colunm names from the subsequent page. Not ideal and is a bit more lifting than I would like jsut to check column names, but it should work.

Also, regarding open sourcing the project, I believe the underlying program is in FORTRAN, so I'm not sure I would be able to make sense of anything from it! Daniel does not at the bottom of [this page](https://users.nber.org/~taxsim/taxsim35/low-level-local.html) that he will provide the source code: "If you need source code I can supply that. It is a single f90 file, and only 2 lines need changing for f77. In that case your compiler will complain about f0.2 and i0 format specifiers. Just change the 0 to 14 for pure f77 code."

**Comment by shanejorr** [comment]
On second thought and look, I will jsut scrape the column names from https://users.nber.org/~taxsim/taxsim35/ and not use the names that appear after clicking 'calculate using this file's data'. I jsut realized that the column names on the latter screen only show up to 6 characters and not the full name.

**Comment by thomascwells** [comment]
For future reference, the debugging JSON output at the bottom of this page might be a good source for column names: https://taxsim.app/. Turn on Developer Mode via the settings-gear at the top right.

**Pull request merged**
